### PR TITLE
Cookie authentication

### LINKED ISSUE #33: Access and refresh token cookies are set after successful login
Described in https://github.com/stormpath/stormpath-framework-spec/blob/master/cookie-authentication.md#authentication-flow

Also assert default cookie flags.

### LINKED ISSUE #34: If access token is invalid, use refresh token to get new access token
Described in https://github.com/stormpath/stormpath-framework-spec/blob/master/cookie-authentication.md#authentication-flow

### LINKED ISSUE #35: If refresh token is invalid, reject request and delete cookies
Described in https://github.com/stormpath/stormpath-framework-spec/blob/master/cookie-authentication.md#authentication-flow

### LINKED ISSUE #36: Reject unauthorized text/html requests with 302 to login route
Described in https://github.com/stormpath/stormpath-framework-spec/blob/master/cookie-authentication.md#rejecting-requests

### LINKED ISSUE #37: Reject unauthorized application/json requests with 401
Described in https://github.com/stormpath/stormpath-framework-spec/blob/master/cookie-authentication.md#rejecting-requests

### LINKED ISSUE #38: Cookie expires flag should be set to token TTL
Described in https://github.com/stormpath/stormpath-framework-spec/blob/master/cookie-authentication.md#cookie-flags

### LINKED ISSUE #121: 302 to login route should preserve original URL including query string
Related to #36

### LINKED ISSUE #232: Passing refresh token as access token should fail
A refresh token passed as an access token should not pass validation.

### PR DESCRIPTION
**Pull request by nbarbettini**
Fixes #33 
Fixes #34 
Fixes #35 
Fixes #36 
Fixes #37 
Fixes #121 
Fixes #38
Fixes #232

### CODE REVIEW

**Comment by nbarbettini** [comment]
Ready for review! :+1:

File: src/test/groovy/com/stormpath/tck/authentication/CookieIT.groovy [hunk 1]
```diff
@@ -0,0 +1,159 @@
...
+    }
+
+    /** Reject unauthorized text/html requests with 302 to login route
+     * 302 to login route should preserve original URL including query string
+     * @see <a href="https://github.com/stormpath/stormpath-framework-tck/issues/36">#36</a>
+     * @see <a href="https://github.com/stormpath/stormpath-framework-tck/issues/121">#121</a>
+     * @throws Exception
+     */
+    @Test(groups=["v100"])
+    public void unauthorizedRequestIsForwardedToLogin() throws Exception {
```
Comment (edjiang) [inline src/test/groovy/com/stormpath/tck/authentication/CookieIT.groovy]: This route shouldn't redirect to `/login` like this, as it's a JSON endpoint. Let me think about how we can test this; we might not be able to do so with the default set of endpoints.

Comment (edjiang) [inline src/test/groovy/com/stormpath/tck/authentication/CookieIT.groovy]: Actually, for `Accept: text/html` depending on how the endpoint is configured it will do this.

**Comment by edjiang** [comment]
Looks great, merging

File: src/test/groovy/com/stormpath/tck/authentication/CookieIT.groovy (hunk 1 above)
Comment (nbarbettini) [inline src/test/groovy/com/stormpath/tck/authentication/CookieIT.groovy]: Yeah, this test is specifically only testing the `Accept: text/html` behavior.
