### PR TITLE
Register route tests

### LINKED ISSUE #179: Serve the registration view model for request type application/json
Described in https://github.com/stormpath/stormpath-framework-spec/blob/master/registration.md#feature-description

### LINKED ISSUE #180: Serve a default HTML form for request type text/html
Described in https://github.com/stormpath/stormpath-framework-spec/blob/master/registration.md#feature-description

### LINKED ISSUE #181: Default form should include fields ordered by fieldOrder

### LINKED ISSUE #188: Re-render form with error if required fields are missing
Described in https://github.com/stormpath/stormpath-framework-spec/blob/master/registration.md#required-fields

### LINKED ISSUE #189: Return JSON error if required fields are missing
Described in https://github.com/stormpath/stormpath-framework-spec/blob/master/registration.md#required-fields

### LINKED ISSUE #194: Re-render form with error if undefined custom field is present
Defined in https://github.com/stormpath/stormpath-framework-spec/blob/master/registration.md#custom-fields

### LINKED ISSUE #195: Return JSON error if undefined custom field is present
Defined in https://github.com/stormpath/stormpath-framework-spec/blob/master/registration.md#custom-fields

### LINKED ISSUE #200: Re-render form and display error if server error occurs
Described in https://github.com/stormpath/stormpath-framework-spec/blob/master/registration.md#-post-error-handling

### LINKED ISSUE #201: Return JSON error if server error occurs
Described in https://github.com/stormpath/stormpath-framework-spec/blob/master/registration.md#-post-error-handling

### LINKED ISSUE #202: Return sanitized JSON account on success
Described in https://github.com/stormpath/stormpath-framework-spec/blob/master/registration.md#-post-response-handling

### LINKED ISSUE #203: Redirect to login page with status=created on success
Described in https://github.com/stormpath/stormpath-framework-spec/blob/master/registration.md#-post-response-handling

### LINKED ISSUE #219: Preserve values in form fields on unsuccessful attempt
If the form is submitted but errors, the values entered in each field should be preserved (with the exception of any password fields).

### PR DESCRIPTION
**Pull request by nbarbettini**
Fixes #179 
Fixes #189 
Fixes #195 
Fixes #201 
Fixes #202 
Fixes #180 
Fixes #181 
Fixes #188 
Fixes #194 
Fixes #200 
Fixes #203 
Fixes #219

### CODE REVIEW

File: src/test/groovy/com/stormpath/tck/register/RegisterIT.groovy [hunk 1]
```diff
@@ -0,0 +1,576 @@
...
+            .body("message", not(isEmptyOrNullString()))
+    }
+
+    /**
+     * Return JSON error if required fields are missing
+     * @see <a href="https://github.com/stormpath/stormpath-framework-tck/issues/189">#189</a>
+     * @throws Exception
+     */
+    @Test
+    public void returnsErrorIfEmailIsMissing() throws Exception {
```
Comment (edjiang) [inline src/test/groovy/com/stormpath/tck/register/RegisterIT.groovy]: rename this to `IfPasswordIsMissing`?

File: src/test/groovy/com/stormpath/tck/register/RegisterIT.groovy [hunk 2]
```diff
@@ -0,0 +1,576 @@
...
+        Map<String, Object>  jsonAsMap = new HashMap<>();
+        jsonAsMap.put("email", accountEmail)
+        jsonAsMap.put("password", accountPassword)
+        jsonAsMap.put("surname", accountSurname)
+        // givenName is required per the default configuration
+
+        given()
+            .accept(ContentType.JSON)
+            .body(jsonAsMap)
+        .when()
```
Comment (edjiang) [inline src/test/groovy/com/stormpath/tck/register/RegisterIT.groovy]: You're missing Content Type headers on a ton of these requests; is RA defaulting to JSON when you're putting these maps in? Otherwise I'm not sure why your code is passing these tests right now...

File: src/test/groovy/com/stormpath/tck/register/RegisterIT.groovy [hunk 3]
```diff
@@ -0,0 +1,576 @@
...
+                .statusCode(200)
+                .contentType(ContentType.HTML)
+            .extract()
+                .response()
+
+        XmlPath doc = getHtmlDoc(response)
+        List<Node> fields = findTags(doc.getNodeChildren("html.body"), "input")
+
+        // From default configuration
+        assertEquals(fields.get(0).attributes().get("name"), "givenName")
```
Comment (edjiang) [inline src/test/groovy/com/stormpath/tck/register/RegisterIT.groovy:300]: Can you grab the fields, and iterate through them to make sure that they're in the right order (but not necessarily index 0)?

File: src/test/groovy/com/stormpath/tck/register/RegisterIT.groovy [hunk 4]
```diff
@@ -0,0 +1,576 @@
...
+        assertThat(warning.toString(), not(isEmptyOrNullString()))
+    }
+
+    /**
+     * Re-render form with error if undefined custom field is present
+     * @see <a href="https://github.com/stormpath/stormpath-framework-tck/issues/194">#194</a>
+     * @throws Exception
+     */
+    @Test
+    public void displaysErrorForUndefinedCustomField() throws Exception {
```
Comment (edjiang) [inline src/test/groovy/com/stormpath/tck/register/RegisterIT.groovy]: It might be overkill to test the validation logic twice... It might be good just to test validation logic for the JSON endpoint and then test that the HTML form displays errors (on a similar error). 

Actually, same with the form fields (instead of iterating through the list, etc); just check the JSON endpoint

File: src/test/groovy/com/stormpath/tck/register/RegisterIT.groovy (hunk 2 above)
Comment (nbarbettini) [inline src/test/groovy/com/stormpath/tck/register/RegisterIT.groovy]: Yeah, RestAssured will auto-detect and apply the right Content-Type header. It wouldn't hurt to specify them, though.

Comment (edjiang) [inline src/test/groovy/com/stormpath/tck/register/RegisterIT.groovy]: Oh ok, it could try to do form data though, no? What hint is it using? 

https://github.com/jayway/rest-assured/wiki/Usage#specifying-request-data

Seems to imply it's using form parameters. Let me try running this with logging mode on to check.

Comment (edjiang) [inline src/test/groovy/com/stormpath/tck/register/RegisterIT.groovy]: I logged this, and it's not doing things correctly:

```
Request method: POST
Request path:   http://localhost:3000/register
Proxy:          <none>
Request params: <none>
Query params:   <none>
Form params:    <none>
Path params:    <none>
Multiparts:     <none>
Headers:        Accept=application/json, application/javascript, text/javascript
                Content-Type=text/plain; charset=ISO-8859-1
Cookies:        <none>
Body:
{"password":"P@sword123!","surname":"Surname-c8cc12da-4928-454e-ad66-233479bb9d87","givenName":"GivenName-c8cc12da-4928-454e-ad66-233479bb9d87","middleName":"Foobar","email":{"values":["fooemail-c8cc12da-4928-454e-ad66-233479bb9d87@stormpath.com"],"strings":["json-",""],"bytes":"anNvbi1mb29lbWFpbC1jOGNjMTJkYS00OTI4LTQ1NGUtYWQ2Ni0yMzM0NzliYjlkODdAc3Rvcm1wYXRoLmNvbQ==","valueCount":1},"username":"foo-c8cc12da-4928-454e-ad66-233479bb9d87"}
```

Let's set the content type properly.

Comment (nbarbettini) [inline src/test/groovy/com/stormpath/tck/register/RegisterIT.groovy]: Huh. I thought I read somewhere that it would apply `application/json` for a Map object. My bad!

File: src/test/groovy/com/stormpath/tck/register/RegisterIT.groovy (hunk 1 above)
Comment (nbarbettini) [inline src/test/groovy/com/stormpath/tck/register/RegisterIT.groovy]: Sure

File: src/test/groovy/com/stormpath/tck/register/RegisterIT.groovy (hunk 3 above)
Comment (nbarbettini) [inline src/test/groovy/com/stormpath/tck/register/RegisterIT.groovy:300]: Probably. Parsing HTML here is extra painful :cry: 

Is the only problem with index>0 because of CSRF currently?

File: src/test/groovy/com/stormpath/tck/register/RegisterIT.groovy (hunk 1 above)
Comment (nbarbettini) [inline src/test/groovy/com/stormpath/tck/register/RegisterIT.groovy]: Ha, didn't even see the typo here.

**Comment by nbarbettini** [comment]
@edjiang See    my experiment at 5af2379 -- adding `json10` and `web10` test groups representing spec 1.0 JSON compliance and spec 1.0 web/forms compliance.

If we did this through the whole TCK, then you could do

```
mvn clean verify -Dgroups=json10
```

to only exercise the JSON endpoints.

File: src/test/groovy/com/stormpath/tck/register/RegisterIT.groovy (hunk 3 above)
Comment (edjiang) [inline src/test/groovy/com/stormpath/tck/register/RegisterIT.groovy:300]: Yep. I don't think the spec says that the "givenName" must be index 0; just that the order is configurable. Since we're not testing configuration right now, I'm not even sure we need this test really. It's also being tested as JSON. 

Topic for discussion for tomorrow!

File: src/test/groovy/com/stormpath/tck/util/TestAccount.groovy [hunk 5]
```diff
@@ -16,23 +16,31 @@ class TestAccount {
...
     String href
 
-    def TestAccount() {
-        def account = [email: email,
-            password: password,
-            givenName: givenName,
-            surname: surname,
-            middleName: middleName,
-            username: username]
+    public static TestAccount create() {
```
Comment (nbarbettini) [inline src/test/groovy/com/stormpath/tck/util/TestAccount.groovy]: @edjiang I made some changes to `TestAccount` that I want to flag with you -- moved the actual (API) creation into a static `create` method. That way, you can do:
- `new TestAccount()` to initialize the class with test data (but don't create anything on the server)
- `TestAccount.create()` to both initialize the test data and create it on the server.

See RegisterIT line 232 for a test that uses the former instead of the latter.

I suppose it could also be implemented as an instance method on `TestAccount` instead of a static method. Let me know if you have any preference.

Comment (edjiang) [inline src/test/groovy/com/stormpath/tck/util/TestAccount.groovy]: Ah, so you can use the test data for testing registration? I think static method makes sense so initialization is easier in other files. Sure, I would just rename `TestAccount.create()` to `TestAccount.registerOnServer()` or something so it's clear what "create" means vs. "new".

Comment (nbarbettini) [inline src/test/groovy/com/stormpath/tck/util/TestAccount.groovy]: Sounds good. Will do.

**Comment by nbarbettini** [comment]
Merging!
